// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 May 2019 10:58:26 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "libpmemkv.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// KVAllCallback_5910e1e is a proxy for callback KVAllCallback.
void KVAllCallback_5910e1e(void* context, int keybytes, char* key);

// KVEachCallback_770981b9 is a proxy for callback KVEachCallback.
void KVEachCallback_770981b9(void* context, int keybytes, char* key, int valuebytes, char* value);

// KVGetCallback_6290ffe is a proxy for callback KVGetCallback.
void KVGetCallback_6290ffe(void* context, int valuebytes, char* value);

// KVStartFailureCallback_206ee003 is a proxy for callback KVStartFailureCallback.
void KVStartFailureCallback_206ee003(void* context, char* engine, char* config, char* msg);