// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 May 2019 10:58:26 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void KVAllCallback_5910e1e(void* context, int keybytes, char* key) {
	kVAllCallback5910E1E(context, keybytes, key);
}

void KVEachCallback_770981b9(void* context, int keybytes, char* key, int valuebytes, char* value) {
	kVEachCallback770981B9(context, keybytes, key, valuebytes, value);
}

void KVGetCallback_6290ffe(void* context, int valuebytes, char* value) {
	kVGetCallback6290FFE(context, valuebytes, value);
}

void KVStartFailureCallback_206ee003(void* context, char* engine, char* config, char* msg) {
	kVStartFailureCallback206EE003(context, engine, config, msg);
}
